//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AviaBuildWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EngTehWorker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EngTehWorker()
        {
            this.EngTehWorkerProfs = new HashSet<EngTehWorkerProf>();
        }
    
        public int IdEngTehWorker { get; set; }
        public string EngTehWorkerName { get; set; }
        public int AreaId { get; set; }
        public bool IsHead { get; set; }
        public bool IsMaster { get; set; }
        public Nullable<int> UnderHeadId { get; set; }
    
        public virtual Area Area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EngTehWorkerProf> EngTehWorkerProfs { get; set; }
    }
}
