//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AviaBuildWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EngTehProf
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EngTehProf()
        {
            this.EngTehWorkerProfs = new HashSet<EngTehWorkerProf>();
        }
    
        public int IdEngTehProf { get; set; }
        public string EngTehProfName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EngTehWorkerProf> EngTehWorkerProfs { get; set; }
    }
}
