//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AviaBuildWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rocket
    {
        public int IdRocket { get; set; }
        public string RocketName { get; set; }
        public string RocketType { get; set; }
        public int RocketProductID { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
