//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AviaBuild
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AviaBuildDBEntities : DbContext
    {
        public AviaBuildDBEntities()
            : base("name=AviaBuildDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Brigade> Brigades { get; set; }
        public virtual DbSet<Ceh> Cehs { get; set; }
        public virtual DbSet<EngTehProf> EngTehProfs { get; set; }
        public virtual DbSet<EngTehWorker> EngTehWorkers { get; set; }
        public virtual DbSet<EngTehWorkerProf> EngTehWorkerProfs { get; set; }
        public virtual DbSet<Plane> Planes { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Prof> Profs { get; set; }
        public virtual DbSet<Rocket> Rockets { get; set; }
        public virtual DbSet<TestEquipment> TestEquipments { get; set; }
        public virtual DbSet<Tester> Testers { get; set; }
        public virtual DbSet<TestLab> TestLabs { get; set; }
        public virtual DbSet<Work> Works { get; set; }
        public virtual DbSet<Worker> Workers { get; set; }
        public virtual DbSet<WorkerProf> WorkerProfs { get; set; }
    
        public virtual ObjectResult<pr1_Result> pr1(string category, Nullable<int> cehId)
        {
            var categoryParameter = category != null ?
                new ObjectParameter("category", category) :
                new ObjectParameter("category", typeof(string));
    
            var cehIdParameter = cehId.HasValue ?
                new ObjectParameter("cehId", cehId) :
                new ObjectParameter("cehId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr1_Result>("pr1", categoryParameter, cehIdParameter);
        }
    
        public virtual ObjectResult<pr10_Result> pr10(Nullable<int> productId)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr10_Result>("pr10", productIdParameter);
        }
    
        public virtual ObjectResult<pr11_Result> pr11(string category, Nullable<int> testLabId, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var categoryParameter = category != null ?
                new ObjectParameter("category", category) :
                new ObjectParameter("category", typeof(string));
    
            var testLabIdParameter = testLabId.HasValue ?
                new ObjectParameter("testLabId", testLabId) :
                new ObjectParameter("testLabId", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr11_Result>("pr11", categoryParameter, testLabIdParameter, startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<pr12_Result> pr12(Nullable<int> productId, string category, Nullable<int> testLabId, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(int));
    
            var categoryParameter = category != null ?
                new ObjectParameter("category", category) :
                new ObjectParameter("category", typeof(string));
    
            var testLabIdParameter = testLabId.HasValue ?
                new ObjectParameter("testLabId", testLabId) :
                new ObjectParameter("testLabId", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr12_Result>("pr12", productIdParameter, categoryParameter, testLabIdParameter, startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<pr13_Result> pr13(Nullable<int> productId, string category, Nullable<int> testLabId, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(int));
    
            var categoryParameter = category != null ?
                new ObjectParameter("category", category) :
                new ObjectParameter("category", typeof(string));
    
            var testLabIdParameter = testLabId.HasValue ?
                new ObjectParameter("testLabId", testLabId) :
                new ObjectParameter("testLabId", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr13_Result>("pr13", productIdParameter, categoryParameter, testLabIdParameter, startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<pr14_Result> pr14(string category, Nullable<int> cehId, Nullable<int> areaId)
        {
            var categoryParameter = category != null ?
                new ObjectParameter("category", category) :
                new ObjectParameter("category", typeof(string));
    
            var cehIdParameter = cehId.HasValue ?
                new ObjectParameter("cehId", cehId) :
                new ObjectParameter("cehId", typeof(int));
    
            var areaIdParameter = areaId.HasValue ?
                new ObjectParameter("areaId", areaId) :
                new ObjectParameter("areaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr14_Result>("pr14", categoryParameter, cehIdParameter, areaIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pr14Count(string category, Nullable<int> cehId, Nullable<int> areaId)
        {
            var categoryParameter = category != null ?
                new ObjectParameter("category", category) :
                new ObjectParameter("category", typeof(string));
    
            var cehIdParameter = cehId.HasValue ?
                new ObjectParameter("cehId", cehId) :
                new ObjectParameter("cehId", typeof(int));
    
            var areaIdParameter = areaId.HasValue ?
                new ObjectParameter("areaId", areaId) :
                new ObjectParameter("areaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pr14Count", categoryParameter, cehIdParameter, areaIdParameter);
        }
    
        public virtual ObjectResult<pr2_Result> pr2(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, string category, Nullable<int> cehId, Nullable<int> areaId)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            var categoryParameter = category != null ?
                new ObjectParameter("category", category) :
                new ObjectParameter("category", typeof(string));
    
            var cehIdParameter = cehId.HasValue ?
                new ObjectParameter("cehId", cehId) :
                new ObjectParameter("cehId", typeof(int));
    
            var areaIdParameter = areaId.HasValue ?
                new ObjectParameter("areaId", areaId) :
                new ObjectParameter("areaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr2_Result>("pr2", startDateParameter, endDateParameter, categoryParameter, cehIdParameter, areaIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pr2Count(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, string category, Nullable<int> cehId, Nullable<int> areaId)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            var categoryParameter = category != null ?
                new ObjectParameter("category", category) :
                new ObjectParameter("category", typeof(string));
    
            var cehIdParameter = cehId.HasValue ?
                new ObjectParameter("cehId", cehId) :
                new ObjectParameter("cehId", typeof(int));
    
            var areaIdParameter = areaId.HasValue ?
                new ObjectParameter("areaId", areaId) :
                new ObjectParameter("areaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pr2Count", startDateParameter, endDateParameter, categoryParameter, cehIdParameter, areaIdParameter);
        }
    
        public virtual ObjectResult<pr3_Result> pr3(Nullable<int> cehId, string engProf, string workerProf)
        {
            var cehIdParameter = cehId.HasValue ?
                new ObjectParameter("cehId", cehId) :
                new ObjectParameter("cehId", typeof(int));
    
            var engProfParameter = engProf != null ?
                new ObjectParameter("engProf", engProf) :
                new ObjectParameter("engProf", typeof(string));
    
            var workerProfParameter = workerProf != null ?
                new ObjectParameter("workerProf", workerProf) :
                new ObjectParameter("workerProf", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr3_Result>("pr3", cehIdParameter, engProfParameter, workerProfParameter);
        }
    
        public virtual ObjectResult<pr4_Result> pr4(Nullable<int> cehId)
        {
            var cehIdParameter = cehId.HasValue ?
                new ObjectParameter("cehId", cehId) :
                new ObjectParameter("cehId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr4_Result>("pr4", cehIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pr4Count(Nullable<int> cehId)
        {
            var cehIdParameter = cehId.HasValue ?
                new ObjectParameter("cehId", cehId) :
                new ObjectParameter("cehId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pr4Count", cehIdParameter);
        }
    
        public virtual ObjectResult<pr5_Result> pr5(Nullable<int> productId)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr5_Result>("pr5", productIdParameter);
        }
    
        public virtual ObjectResult<pr6_Result> pr6(Nullable<int> cehId, Nullable<int> areaId)
        {
            var cehIdParameter = cehId.HasValue ?
                new ObjectParameter("cehId", cehId) :
                new ObjectParameter("cehId", typeof(int));
    
            var areaIdParameter = areaId.HasValue ?
                new ObjectParameter("areaId", areaId) :
                new ObjectParameter("areaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr6_Result>("pr6", cehIdParameter, areaIdParameter);
        }
    
        public virtual ObjectResult<pr7_Result> pr7(Nullable<int> cehId, Nullable<int> areaId)
        {
            var cehIdParameter = cehId.HasValue ?
                new ObjectParameter("cehId", cehId) :
                new ObjectParameter("cehId", typeof(int));
    
            var areaIdParameter = areaId.HasValue ?
                new ObjectParameter("areaId", areaId) :
                new ObjectParameter("areaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr7_Result>("pr7", cehIdParameter, areaIdParameter);
        }
    
        public virtual ObjectResult<pr8_Result> pr8(string category, Nullable<int> cehId, Nullable<int> areaId)
        {
            var categoryParameter = category != null ?
                new ObjectParameter("category", category) :
                new ObjectParameter("category", typeof(string));
    
            var cehIdParameter = cehId.HasValue ?
                new ObjectParameter("cehId", cehId) :
                new ObjectParameter("cehId", typeof(int));
    
            var areaIdParameter = areaId.HasValue ?
                new ObjectParameter("areaId", areaId) :
                new ObjectParameter("areaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr8_Result>("pr8", categoryParameter, cehIdParameter, areaIdParameter);
        }
    
        public virtual ObjectResult<pr9_Result> pr9(Nullable<int> productId)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr9_Result>("pr9", productIdParameter);
        }
    }
}
