//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AviaBuild
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class EngTehWorkerProf
    {
        public int EngTehWorkerId { get; set; }
        public int EngTehProfId { get; set; }
        public Nullable<System.DateTime> StartWorkDate { get; set; }
        public Nullable<System.DateTime> QuitDate { get; set; }
    
        public virtual EngTehProf EngTehProf { get; set; }
        public virtual EngTehWorker EngTehWorker { get; set; }
    }
}
