//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AviaBuild
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Plane
    {
        public int IdPlane { get; set; }
        public string PlaneName { get; set; }
        public string PlaneType { get; set; }
        public int PlaneProductID { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
