//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AviaBuild
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class WorkerProf
    {
        public int WorkerId { get; set; }
        public int ProfId { get; set; }
        public Nullable<System.DateTime> StartWorkDate { get; set; }
        public Nullable<System.DateTime> QuitDate { get; set; }
    
        public virtual Prof Prof { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
